### ISSUE TITLE
可以提供一个demo么？

### ISSUE THREAD

**Issue by chudaozhe** [lysily1314/alibaba1688#1]
比如“发布商品”接口应该怎么调用？

**Comment by lysily1314** [comment]
$client = new AlibabaCross();
$request = new CategoryGetParams($cid);
//如果有其他参数
//$request-&gt;字段 = 值
$client-&gt;category-&gt;categoryGet($request)-&gt;get();//或者-&gt;post();




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lysily1314/alibaba1688"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月6日(星期六) 中午1:52
收件人:&nbsp;"lysily1314/alibaba1688"<alibaba1688@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [lysily1314/alibaba1688] 可以提供一个demo么？ (#1)





 
Closed #1.
